index.js, package.json, slack.js, test/index.test.js, test/slack.test.js
It would be convenient to receive slack notifications when things happen in a pipeline, so users can respond appropriately to successful deploy, or when the pipeline fails.
Provide an interface that allows users to receive pipeline notifications via slack. Users specify the channels which should receive notifications, and build statuses that trigger a notification.
In `screwdriver.yaml`
```
settings:
slack: channel_A
```
```
settings:
slack: [channel_A, channel_B]
```
```
settings:
slack: 
channels: 
- channel_A
- channel_B
statuses:
- SUCCESS
- FAILURE
- ABORTED
- QUEUED
- RUNNING
```
https://github.com/screwdriver-cd/screwdriver/issues/687
=> feat(687): implement _notify for slack

screwdriver.yaml
use semantic-release template to publish since the latest semantic release requires node 8
=> fix: use semantic-release template to publish

slack.js
The [default retry config is set to forever with exponential backoff](https://slackapi.github.io/node-slack-sdk/web_api#changing-the-retry-configuration). This is causing *rate_limiting errors* for us. We should set a more reasonable max number of retries.
```
[INFO] @slack/client:WebClient0 API Call failed due to rate limiting. Will retry in 3 seconds.
```
This PR sets more reasonable retry options. 
- Retry options: https://github.com/tim-kos/node-retry#tutorial
- Current default retry option: https://github.com/slackapi/node-slack-sdk/blob/fec79509a10ed574c260c3bea68b839bd46970c1/src/retry-policies.ts#L30
- Slack client docs: https://slackapi.github.io/node-slack-sdk/web_api#changing-the-retry-configuration
=> fix: Set max number of retries to 5

README.md, slack.js, test/index.test.js, test/slack.test.js
We're getting rate limited from Slack for all our calls to `channels.list`. We make these calls every time we post notifications to Slack in order to get the channel ID. After further research, it looks like you don't need the channel ID in order to post a message. 
This PR removes calls to `channels.list` in favor of just posting to the channel name directly. The `chat.postMessage` endpoint has a much more relaxed rate limit (1 message per second to a specific channel, which translates into several hundred messages per minute; much better than the 20 per minute per workspace for `channels.list`), which should also help our rate limiting issue. 
_Note: The documentation says you need a `#` before the channel name for a public channel and no `#` for a private one, but when I tried running …
=> fix: Use channel name to post Slack notification, avoid rate limits

index.js, test/index.test.js
We found Joi validation error. So I modified to change `branch` and `url` to optional value.
```
"pipeline": {
"scmRepo": {
"name": "wahapo/wahapo-test",
"url" [2]: "https://github.com/wahapo/wahapo-test/tree/master",
"branch" [1]: "master"
},
(Omitted)
[1] "branch" is not allowed
[2] "url" is not allowed
```
Related: https://github.com/screwdriver-cd/screwdriver/pull/1368
BugFix for: https://github.com/screwdriver-cd/notifications-slack/pull/13
=> fix: bug fix SCHEMA_SCM_REPO

index.js, test/index.test.js
Currently, notification message which is sent to slack has little information about a build.
I added commit information to notification message and refine message style.
Fix message body and attachment fields.
New notification message like below.
=> feat: Enrich notification message

index.js, test/index.test.js
**Issue #, if available:**
It resembles to [1177](https://github.com/screwdriver-cd/screwdriver/issues/1177)
**Description of changes:**
Ower users wants to inject their arbitrarily message to slack notification, to check any values in the middle of building. This PR provide the function to deliver arbitrarily message  by setting meta.
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> feat(1177): Add meta message

README.md, package.json, screwdriver.yaml, test/index.test.js
hapi npm package is deprecated in favor of @hapi/hapi.
This PR:
- removes jenkins-mocha in favor of mocha and nyc
- replaces hapi with @hapi/hapi
- replaces node:8 with node:12 in the screwdriver.yaml
=> fix: Update Hapi and node versions

.gitignore, index.js, test/index.test.js
Having `notification.slack.message` set is useful for a generic message that is tight to the same event across a pipeline.
https://docs.screwdriver.cd/user-guide/metadata.html#notifications
This isn’t optimal though when you have parallel jobs and the generic message was set in one of the jobs and may only apply to that specific job. The work around is that in every parallel job `notification.slack.message` would have to be reset which adds additional setup to your yaml.
Allowing to overwrite the generic `notification.slack.message` with `notification.slack.<jobName>.message` will make this easier.
In the use cases where job specific slack messages are needed a user can now set `notification.slack.<jobName>.message`, which will overwrite the generic `notification.slack.message`, if it was …
=> feat: Allow setting job specific slack message

index.js, test/index.test.js
`meta set build.meta.notification.slack.{jobname}.channels` can be used to overwrite the yaml defined slack channel.
Overwrites are specific to the current job.
It can be a comma separated string for multiple channels. This will only work to overwrite a yaml set slack channel. It is not a replacement.
This is useful when code inside a SD step decides who should be notified.
=> feat: Allow to set slack channel per job dynamically

index.js
Overwriting `buildData.settings.slack` breaks slack notification. The previous logic of how to set up slack channels and statuses has to run first.  With this change https://github.com/screwdriver-cd/notifications-slack/pull/28 is working correctly. 
=> [Bug Fix] Fix channel overwrite using meta data

index.js, test/index.test.js
feat: https://github.com/screwdriver-cd/screwdriver/issues/1572
This PR adds the status "FIXED" when a build has failed in the past and the build succeeds again.
Notification-slack-plugin receives a build status label (`isFIxed`) from screwdriver api.
Therefore, The "FIXED" status uses the same `COLOR_MAP` and `STATUSES_MAP` as the "SUCCESS" status.
In order for users to receive FIXED notifications, "FAILURE" must be set to screwdriver.yaml.
The image below is a FIXED notification sent by slack.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1572
[1] notifications-email https://github.com/screwdriver-cd/notifications-email/pull/22
[3]  screwdriver-api https://github.com/screwdriver-cd/screwdriver/pull/2182
[4] guide screwdriver-cd/guide#407
I confirm that this contribution is …
=> feat(1572): [2] Add FIXED status to the build

index.js, package.json
Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/joi version and fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958
=> feat(1958): Upgrade hapi dependencies. BREAKING CHANGE: hapi v19

index.js, test/index.test.js
Add feature https://github.com/screwdriver-cd/screwdriver/issues/2022
Add the `Source Directory` setting as notification message.
Below is example of slack:
https://github.com/screwdriver-cd/screwdriver/issues/2022
https://github.com/screwdriver-cd/screwdriver/issues/2005
https://github.com/screwdriver-cd/notifications-email/pull/24
=> feat(2022): add source dir message

index.js, package.json
The same definitions exist for both [notification-email](https://github.com/screwdriver-cd/notifications-email/blob/e9906f2601e50cddaf21e80b877992d01332ac34/index.js#L54-L62) and [notification-slack](https://github.com/screwdriver-cd/notifications-slack/blob/59f18306297795c4288591f562a552396ccacd72/index.js#L66-L74), and it is possible that the next time we add a feature, we will miss a fix for one or the other.
The definitions that exist in both [notification-email](https://github.com/screwdriver-cd/notifications-email/blob/e9906f2601e50cddaf21e80b877992d01332ac34/index.js#L54-L62) and [notification-slack](https://github.com/screwdriver-cd/notifications-slack/blob/59f18306297795c4288591f562a552396ccacd72/index.js#L66-L74) are combined in one place.
Merging …
=> [2] fix: require screwdriver-data-schema@20.6.0

index.js, test/index.test.js
Using meta data`notification.slack.jobname.minimized` will allow overwriting the default minimized setting from within a job.
Feature request: https://github.com/screwdriver-cd/screwdriver/issues/2284
Documentation: https://github.com/screwdriver-cd/guide/pull/433
=> Allow setting minimized from within Job

index.js, test/index.test.js
Currently, `Joi.validate()` is [not exist](https://github.com/sideway/joi/issues/1941).
```
TypeError: Joi.validate is not a function
```
We shold use [`schema.validate()`](https://github.com/sideway/joi/issues/2145#issuecomment-568173652) instead.
This PR enables `validateConfig()` for [config-parser](https://github.com/screwdriver-cd/config-parser/pull/105/files).
https://github.com/screwdriver-cd/screwdriver/issues/2051
[1] : this PR
[2] : https://github.com/screwdriver-cd/notifications-email/pull/29
[3]: https://github.com/screwdriver-cd/config-parser/pull/115
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
=> [1] fix(2051): fix function that does not exist

package.json, slack.js, test/index.test.js, test/slack.test.js
`@slack/client` npm package has been deprecated in favor of `@slack/web-api`: https://www.npmjs.com/package/@slack/client
This PR updates the npm package to use latest `@slack/web-api`
See https://github.com/screwdriver-cd/notifications-slack/pull/39
=> fix: Update Slack client npm package to web-api v5

index.js, test/index.test.js
Even PR builds have a link to `/pipelines/{id}` in slack messages.
For PR builds, set the link to `/pipelines/{id}/pulls` which is the page with the Pull Requests tab selected.
=> fix: set the link to /pipelines/{id}/pulls for PR builds

index.js, package.json, slack.js, test/index.test.js, test/slack.test.js
**BREAKING CHANGE: Slack notification config is changed. It must be changed to the new configuration format.**
This PR is the implementation of this.
https://github.com/screwdriver-cd/screwdriver/issues/2505#issuecomment-1668815410
Support multi workspace slack notification.
Users can specify a workspace as bellow:
```yaml
settings:
slack:
channels:
- test-channel-1  # Send to test-channel-1 in default workspace.
- workspace1:test-channel-2  # Send to test-channel-2 in workspace1
- workspace2:test-channel-1  # Send to test-channel-1 in workspace2
```
Issue 
- https://github.com/screwdriver-cd/screwdriver/issues/2505
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …
=> [1] feat(2505): multi workspace slack notification

index.js, test/index.test.js
Sometime, uses want to skip slack notifications.
However, they cannot control whether slack notifications are sent using metadata of `notification.slack.${SD_JOB_NAME}.channels`.
This PR allows uses to skip slack notifications by setting an empty string in the metadata as shown below.
```yaml
jobs:
not-notify:
requires: [ ~commit ]
image: node:20
settings:
slack:
channels:
- your-channel
statuses:
- SUCCESS
steps:
- echo: meta set notification.slack.${SD_JOB_NAME}.channels ""
```
=> feat: skip post slack notification when meta.channel is empty string
